# Generated by Django 4.0.1 on 2022-01-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=400)),
                ('Description', models.TextField()),
                ('Cost_per_item', models.BigIntegerField()),
                ('stock_quantity', models.BigIntegerField()),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
